### ISSUE TITLE
Broken Collab links

### ISSUE THREAD

**Issue by rodigu** [UdayLab/PAMI#224]
The links under [7. Mining interesting patterns from sequence databases](https://github.com/UdayLab/PAMI#7-mining-interesting-patterns-from-sequence-databases) are broken:

![image](https://github.com/UdayLab/PAMI/assets/58960796/e6eb5adc-06d3-4d3c-9523-8148473374f1)

**Comment by udayRage** [comment]
Thank you very much for your feedback. We have rectified the link problem. Please check it now.
