### ISSUE TITLE
Bug in PAMI/fuzzyCorrelatedPattern/basic/FCPGrowth.py --> list index out of range

### ISSUE THREAD

**Issue by vanithakattumuri** [UdayLab/PAMI#256]
[/usr/local/lib/python3.10/dist-packages/PAMI/fuzzyCorrelatedPattern/basic/FCPGrowth.py] in _creatingItemSets(self)
 420                             parts = line.split(":")
   421                             items = parts[0].split()
--> 422                             quantities = parts[2].split()
    423                             self._transactions.append([x for x in items])
    424                             self._fuzzyValues.append([x for x in quantities])

IndexError: list index out of range

**Comment by udayRage** [comment]
Vanitha, has the problem been resolved?

If yes, let us close this issue. Otherwise, please request Nakamura-san to resolve it.
