### ISSUE TITLE
parallelFPGrowth seems to ignore sep

### ISSUE THREAD

**Issue by netogallo** [UdayLab/PAMI#356]
Greetings,

I was trying to use parallelFPGrowth on a space separated database w/o any success. Then I noticed that in:

https://github.com/UdayLab/PAMI/blob/66bec6b1cf89588657887194b5dccb25f1d10855/PAMI/frequentPattern/pyspark/parallelFPGrowth.py#L275

One has:

``
rdd = sc.textFile(self._iFile, self._numPartitions)\
        .map(lambda x: x.rstrip().split('\t'))\
        .persist()
``

I believe the correct implementation is:

``
rdd = sc.textFile(self._iFile, self._numPartitions)\
        .map(lambda x: x.rstrip().split(self._sep))\
        .persist()
``

**Comment by udayRage** [comment]
Thank you very much for letting us know about the bug.

We will resolve it ASAP (mostly today) and release a new version.

**Comment by netogallo** [comment]
You are welcome! Thank you for looking at it.

**Comment by netogallo** [comment]
I did not issue a Pull Request as this is a one liner. However, I noticed that the other parallel algorithms (parallelApiori, parallelECLAT) very similar code. If there is interest from your end, I am happy to issue a pull request to abstract the repeated code into a consolidated location.

**Comment by udayRage** [comment]
thanks for your email and support.


Plz make necessary changes in the algorithms and send pull request. we will
gadly accept the request.

Thanks for the contribution.

Regards

Prof. Rage Uday Kiran
Leader of Aizu Research Cluster (B) - iTransporation
Associate Professor
Division of Information Systems
University of Aizu, Aizu-Wakamatsu, Japan.

Lab number: 145-A

Mobile no. +81 80 4834 0999
Phone no. (Lab) +81 242 37 2541
                  (Ext) 3115


----------------------------------------------------------------------
When people throw stones at you, convert them into milestones.

**Comment by udayRage** [comment]
We have corrected the bugs you reported. Thank you very much for your support. 

We will now close this issue.
