### ISSUE TITLE
Association Rules as method instead of subclass

### ISSUE THREAD

**Issue by CharlieAprog** [UdayLab/PAMI#386]
Hey there, nice stuff so far.
I am a bit confused as to why there is no (convenient/clear) option to acquire the assotiation rules and rank then according to lift after running a basic frequent patern mining algorithm. Instead its hidden inside a separate class that spceifically creates association rules rather than it being an extension to any algorithm run. Could you consider adapting this to become a general method of the basic pattern miners?

**Comment by CharlieAprog** [comment]
Hey there thank for the great information and quick response

I agree with you that the two should be kept separate, of course. The
reason why i was asking was because moving from the currently formatted
results in pami to association rule mining is very strange. It required a
path to a dataset, rather than accepting the results directly from a
frequent pattern algorithm.
Besides research being more interested in frequent patterns, allowing for a
more accessible route to life values allows for a simple and quick way to
not only obtain frequent patterns, but also evaluate their usefulness and
validity somewhat. My suggestion to add a method was not to include it in
each mine() operation, but to allow easy access to rules, once mining has
been done, if wanted.

Thanks again for the email
Charlie

**Comment by udayRage** [comment]
Q) It required a path to a dataset, rather than accepting the results directly from a frequent pattern algorithm.
Ans) No need. 
   First, you can generate  frequent patterns and store them in a dataframe using obj.getPatternsAsDataFrame()
  Second, just pass the frequent pattern data frame into a rule mining algorithm to generate rules. 

   You don't need to save the patterns in a file and read again from a file, which is a time consuming and computationally expensive operation. 

   I will ask my students tomorrow to check.  We will check the code tomorrow and update you in the comments.

**Comment by udayRage** [comment]
Dear Charlie,

Good day!

    Thank you very much for your valuable feedback.

       We have incorporated your suggestion and modified the Association rule mining code to accept the data frame as an input and output association rules.

    Please check the below provided jupyter notebook. 

[Google Collab](https://colab.research.google.com/github/UdayLab/PAMI/blob/main/notebooks/associationRules/basic/confidence.ipynb
)

**Comment by udayRage** [comment]
Dear Charlie,

Good day!

    Thank you very much for your valuable feedback.

       We have incorporated your suggestion and modified the Association rule mining code to accept the data frame as an input and output association rules.

    Please check the below provided jupyter notebook. 

[Google Collab](https://colab.research.google.com/github/UdayLab/PAMI/blob/main/notebooks/associationRules/basic/confidence.ipynb
)

**Comment by udayRage** [comment]
We will now close this issue.

IF you find any further issues, please feel free to inform us, and we will be glad to incorporate them.
