### ISSUE TITLE
Bug in PAMI.extras.graph.visualizePatterns.py

### ISSUE THREAD

**Issue by udayRage** [UdayLab/PAMI#61]
from PAMI.extras.graph import visualizePatterns as fig

obj = fig.visualizePatterns('soramame_frequentPatterns.txt',10)
obj.visualize()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-8773443ae981> in <cell line: 4>()
      2 
      3 obj = fig.visualizePatterns('soramame_frequentPatterns.txt',10)
----> 4 obj.visualize()

/usr/local/lib/python3.10/dist-packages/PAMI/extras/graph/visualizePatterns.py in visualize(self)
     62                 temp = points[i].split()
     63                 if i % 2 == 0:
---> 64                     lat.append(float(temp[0]))
     65                     name.append(freq)
     66                     color.append("#" + RHex + GHex + BHex)

ValueError: could not convert string to float: 'oint(130.7998865'

**Comment by Likhitha-palla** [comment]
Solved the bug and updated the code.

**Comment by udayRage** [comment]
Likhitha, before closing, please execute this code at https://github.com/UdayLab/PAMI/blob/main/notebooks/airPollutionAnalytics.ipynb


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-14-8773443ae981>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 obj = fig.visualizePatterns('soramame_frequentPatterns.txt',10)
----> 4 obj.visualize()

[/usr/local/lib/python3.10/dist-packages/PAMI/extras/graph/visualizePatterns.py](https://localhost:8080/#) in visualize(self)
     57             for i in range(len(points)):
     58                 temp = points[i].split()
---> 59                 lat.append(float(temp[0]))
     60                 long.append(float(temp[1]))
     61                 name.append(freq)

ValueError: could not convert string to float: 'd'
