### ISSUE TITLE
Bug in maxFPgrowth algorithm

### ISSUE THREAD

**Issue by udayRage** [UdayLab/PAMI#64]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 2
      1 obj = alg.MaxFPGrowth(iFile=inputFile, minSup=minimumSupportCount, sep=seperator)    #initialize
----> 2 obj.startMine()            #Start the mining process

File ~/Library/CloudStorage/Dropbox/Github/PAMI_new/PAMI/frequentPattern/maximal/MaxFPGrowth.py:661, in MaxFPGrowth.startMine(self)
    659 self._finalPatterns = {}
    660 self._maximalTree = _MPTree()
--> 661 Tree = self._buildTree(updatedTransactions, info, self._maximalTree)
    662 Tree.generatePatterns([], patterns)
    663 for x, y in patterns.items():

TypeError: _buildTree() takes 2 positional arguments but 3 were given

**Comment by Likhitha-palla** [comment]
Respected Sir,

Cleared the bug.
