### ISSUE TITLE
Bug in parallelECLAT

### ISSUE THREAD

**Issue by udayRage** [UdayLab/PAMI#65]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 obj = alg.parallelECLAT(iFile=inputFile, minSup=minimumSupportCount,numWorkers=mumberWorkersCount, sep=seperator)    #initialize
      2 obj.startMine()            #Start the mining process

TypeError: Can't instantiate abstract class parallelECLAT with abstract methods printResults, save

**Comment by Likhitha-palla** [comment]
Solved
