### ISSUE TITLE
Bug in parallelApriori

### ISSUE THREAD

**Issue by udayRage** [UdayLab/PAMI#66]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 obj = alg.parallelApriori(iFile=inputFile, minSup=minimumSupportCount,numWorkers=mumberWorkersCount, sep=seperator)    #initialize
      2 obj.startMine()            #Start the mining process

TypeError: Can't instantiate abstract class parallelApriori with abstract methods printResults, save

**Comment by Likhitha-palla** [comment]
Solved
