### ISSUE TITLE
Bug in RSFP-growth (PAMI.relativeFrequentPattern.basic)

### ISSUE THREAD

**Issue by udayRage** [UdayLab/PAMI#67]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 obj = alg.RSFPGrowth(iFile=inputFile, minSup=minimumSupportCount, minRatio=minRatioEx,sep=seperator)    #initialize
      2 obj.startMine()            #Start the mining process

TypeError: __init__() got an unexpected keyword argument 'minSup'

**Comment by Likhitha-palla** [comment]
Solved
