### ISSUE TITLE
Bug in createTemporal(), 

### ISSUE THREAD

**Issue by udayRage** [UdayLab/PAMI#87]
When we convert a data frame into a temporal database, the first column, i.e., timestamp in the constructed database contains 0.

However, we all know that the timestamp of the first transaction will always be greater than or equal 1. (Never cannot be zero).

So we have to change the code so that the temporal database contains timestamp starting from 1 (and from 0).

Check Step 6 in https://github.com/UdayLab/PAMI/blob/main/notebooks/periodicFrequentPatternMiningPollutionDemo.ipynb

               !head -5 temporalDatabasePM25HeavyPollution.csv

**Comment by udayRage** [comment]
We must also replace the separator 'comma' with the default separator 'tab space.'

**Comment by Likhitha-palla** [comment]
Solved
